# cluster specific values
cluster:
  # specify cluster name
  name: 3-ctrl-2-worker-rke2

  # specify cluster labels
  labels: {}

  # specify cluster annotations
  annotations: {}

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: ""

